/*
   3D model generated by Jo Map Editor v6.1
*/

#ifndef __3D_MODELBANDANA_H__
# define __3D_MODELBANDANA_H__

static POINT    PointGrp7[] =
{
	{659829, 1348453, 664660},
	{659829, 1348453, 664660},
	{-529757, 47897, -311184},
	{-663268, 3051331, 992120},
	{674561, 3021947, 762603},
	{-598432, 2758032, 894854},
	{661568, 2729955, 697839},
	{896080, 2729955, 177009},
	{909073, 3021947, 241772},
	{557875, 2984805, -681464},
	{570868, 3276800, -616701},
	{557875, 2984805, -681464},
	{570868, 3276800, -616701},
	{-533903, 2655492, -856524},
	{-520909, 2947486, -791761},
	{-861720, 2488634, 83813},
	{-848727, 2780626, 148576},
};

static POLYGON    PolygonGrp7[] =
{
	{{-10248, 18322, -62082}, {4, 5, 3, 3}},
	{{18322, -62082, -59246}, {6, 8, 7, 7}},
	{{-62082, -59246, 8553}, {8, 9, 7, 7}},
	{{-59246, 8553, -26676}, {10, 11, 9, 9}},
	{{8553, -26676, -61177}, {11, 14, 13, 13}},
	{{-26676, -61177, -2461}, {14, 15, 13, 13}},
	{{-61177, -2461, 23370}, {5, 16, 3, 3}},
	{{-2461, 23370, 0}, {4, 6, 5, 5}},
	{{23370, 0, 0}, {6, 4, 8, 8}},
	{{0, 0, 65536}, {8, 10, 9, 9}},
	{{-59246, 8553, -26676}, {10, 12, 11, 11}},
	{{0, 65536, -6039}, {11, 12, 14, 14}},
	{{65536, -6039, -13874}, {14, 16, 15, 15}},
	{{-6039, -13874, 63765}, {5, 15, 16, 16}},
};

static ATTR    AttributeGrp7[] =
{
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
};

jo_3d_mesh    MeshGrp7 =
{
	.data =
	{
		PointGrp7,
		17,
		PolygonGrp7,
		14,
		AttributeGrp7
	}
};

/* Call this function in you code to display all objects */
static __jo_force_inline void       display_bandana_mesh(void)
{
	jo_3d_mesh_draw(&MeshGrp7);
}

#endif /* !__3D_MODELBANDANA_H__ */
