/*
   3D model generated by Jo Map Editor v6.1
*/

#ifndef __3D_MODELFOAM_H__
# define __3D_MODELFOAM_H__

static POINT    Pointwaveattemt2COMwave17821Material1001[] =
{
	{-693104, 2632908, -8627636},
	{-664337, 2383697, -8730914},
	{-770539, 1515950, -1925419},
	{-741772, 1266739, -2028692},
	{814702, 2916107, -10511339},
	{741058, 3223111, -10453150},
	{-711044, 2770544, -8664144},
	{-637401, 2463540, -8722338},
	{1682017, 2251963, -11359886},
	{1710661, 2632428, -11519095},
	{953569, 3276800, -10602049},
	{924925, 2896334, -10533901},
	{1696511, 2316510, -11818418},
	{1713795, 2292861, -11419416},
	{1939016, 1630706, -11334508},
	{1922612, 1651764, -11733176},
};

static POLYGON    Polygonwaveattemt2COMwave17821Material1001[] =
{
	{{-65161, -6743, -1876}, {0, 3, 2, 2}},
	{{-6743, -1876, -50268}, {5, 7, 6, 6}},
	{{-1876, -50268, -4126}, {9, 11, 10, 10}},
	{{-50268, -4126, -41845}, {15, 13, 12, 12}},
	{{-4126, -41845, -51601}, {9, 13, 8, 8}},
	{{-41845, -51601, -3326}, {5, 11, 4, 4}},
	{{-51601, -3326, -40263}, {0, 7, 1, 1}},
	{{-3326, -40263, -62086}, {0, 1, 3, 3}},
	{{-40263, -62086, -20931}, {5, 4, 7, 7}},
	{{-62086, -20931, 1448}, {9, 8, 11, 11}},
	{{-20931, 1448, -53492}, {15, 14, 13, 13}},
	{{1448, -53492, -11117}, {9, 12, 13, 13}},
	{{-53492, -11117, -36192}, {5, 10, 11, 11}},
	{{-11117, -36192, -11391}, {0, 6, 7, 7}},
};

static ATTR    Attributewaveattemt2COMwave17821Material1001[] =
{
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
};

jo_3d_mesh    Meshwaveattemt2COMwave17821Material1001 =
{
	.data =
	{
		Pointwaveattemt2COMwave17821Material1001,
		16,
		Polygonwaveattemt2COMwave17821Material1001,
		14,
		Attributewaveattemt2COMwave17821Material1001
	}
};

/* Call this function in you code to display all objects */
static __jo_force_inline void       display_foam_mesh(void)
{
	jo_3d_mesh_draw(&Meshwaveattemt2COMwave17821Material1001);
}

#endif /* !__3D_MODELFOAM_H__ */
