/*
   3D model generated by Jo Map Editor v6.1
*/

#ifndef __3D_MODELTRUNKS_H__
# define __3D_MODELTRUNKS_H__

static POINT    PointGrp4[] =
{
	{-455588, 3147517, 154368},
	{200669, 3276800, 292779},
	{200669, 3276800, 292779},
	{-455588, 3147517, 154368},
	{-503845, 1221710, -268532},
	{385011, 1217098, 335677},
	{-562645, 996909, -210114},
	{-562645, 1001344, 344059},
	{-78531, 1007296, -205923},
	{-78531, 944044, 344059},
	{415584, 910734, -210114},
	{415584, 915169, 344059},
	{-2311, 1154497, -156823},
	{377034, 439363, -196443},
	{377034, 439363, 285142},
	{-24671, 439363, 285142},
	{-24671, 439363, -196443},
	{-619926, -8136, 498980},
	{-277314, 1254643, 306674},
	{-455831, 1250580, 297018},
	{-504494, 1225610, -148908},
	{-507817, 1249997, 283216},
	{329124, 1209531, -214244},
	{385011, 1213361, -35001},
	{-397228, 1257450, 302284},
	{-292968, 1221341, -266218},
	{-389489, 1223600, -150416},
	{-461902, 1225536, -268602},
	{-785385, 3020791, 181390},
	{-555331, 441514, 285142},
	{-555331, 441514, -196443},
	{-153625, 441514, 285142},
	{-153625, 441514, -196443},
};

static POLYGON    PolygonGrp4[] =
{
	{{-46496, -21658, -40791}, {6, 21, 4, 4}},
	{{-42621, -22330, 44493}, {8, 7, 6, 6}},
	{{-42621, -22330, 44493}, {8, 11, 9, 9}},
	{{-21658, -40791, -42621}, {21, 9, 5, 5}},
	{{-43674, 1714, -25779}, {13, 15, 16, 16}},
	{{1714, -25779, -60228}, {10, 14, 13, 13}},
	{{-25779, -60228, -45110}, {16, 10, 13, 13}},
	{{-60228, -45110, -17614}, {23, 5, 11, 11}},
	{{-40791, -42621, -22330}, {4, 20, 27, 27}},
	{{44493, -34626, 34474}, {11, 5, 9, 9}},
	{{-42621, -22330, 44493}, {8, 22, 10, 10}},
	{{-46496, -21658, -40791}, {6, 25, 8, 8}},
	{{46084, -2216, -20427}, {18, 21, 5, 5}},
	{{-46496, -21658, -40791}, {6, 7, 21, 21}},
	{{-42621, -22330, 44493}, {8, 9, 7, 7}},
	{{-42621, -22330, 44493}, {8, 10, 11, 11}},
	{{-21658, -40791, -42621}, {21, 7, 9, 9}},
	{{-2216, -20427, 62231}, {11, 15, 14, 14}},
	{{-20427, 62231, 38006}, {9, 16, 15, 15}},
	{{44156, 46570, -1548}, {22, 21, 27, 27}},
	{{44493, -34626, 34474}, {11, 10, 23, 23}},
	{{44156, 46570, -1548}, {22, 23, 10, 10}},
	{{-42621, -22330, 44493}, {8, 25, 22, 22}},
	{{-46496, -21658, -40791}, {6, 4, 25, 25}},
	{{46084, -2216, -20427}, {18, 24, 21, 21}},
	{{38006, -29555, 44462}, {29, 6, 30, 30}},
	{{-29555, 44462, 0}, {6, 32, 30, 30}},
	{{44462, 0, -65536}, {32, 9, 31, 31}},
	{{0, -65536, 0}, {9, 29, 31, 31}},
	{{-43674, 1714, -25779}, {32, 29, 30, 30}},
	{{-65536, 0, 65317}, {10, 9, 11, 11}},
	{{0, 65317, -5341}, {13, 14, 15, 15}},
	{{65317, -5341, 0}, {10, 11, 14, 14}},
	{{-5341, 0, 0}, {16, 8, 10, 10}},
	{{0, 0, -1899}, {11, 9, 15, 15}},
	{{0, -1899, -65508}, {9, 8, 16, 16}},
	{{44156, 46570, -1548}, {22, 5, 21, 21}},
	{{-1899, -65508, 64373}, {29, 7, 6, 6}},
	{{-65508, 64373, 10340}, {6, 8, 32, 32}},
	{{64373, 10340, -6640}, {32, 8, 9, 9}},
	{{10340, -6640, -5954}, {9, 7, 29, 29}},
	{{-43674, 1714, -25779}, {32, 31, 29, 29}},
	{{-6640, -5954, 65229}, {10, 8, 9, 9}},
};

static ATTR    AttributeGrp4[] =
{
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
};

jo_3d_mesh    MeshGrp4 =
{
	.data =
	{
		PointGrp4,
		33,
		PolygonGrp4,
		43,
		AttributeGrp4
	}
};

/* Call this function in you code to display all objects */
static __jo_force_inline void       display_trunks_mesh(void)
{
	jo_3d_mesh_draw(&MeshGrp4);
}

#endif /* !__3D_MODELTRUNKS_H__ */
