/*
   3D model generated by Jo Map Editor v6.1
*/

#ifndef __3D_MODELBOARD_H__
# define __3D_MODELBOARD_H__

static POINT    PointPlane[] =
{
	{-3276800, -408152, 0},
	{-3276800, -168752, 0},
	{3276800, -732009, 0},
	{3276800, 971465, 0},
	{-641305, 1233488, 0},
	{2419269, 1590860, 0},
	{-610555, -1476442, 0},
	{2392795, -1598206, 0},
};

static POLYGON    PolygonPlane[] =
{
	{{0, 0, 65536}, {4, 1, 6, 6}},
	{{0, 0, 65536}, {0, 6, 1, 1}},
	{{0, 0, 65536}, {6, 7, 4, 4}},
	{{0, 0, 65536}, {7, 2, 5, 5}},
	{{0, 0, 65536}, {2, 3, 5, 5}},
	{{0, 0, 65536}, {5, 4, 7, 7}},
};

static ATTR    AttributePlane[] =
{
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
};

jo_3d_mesh    MeshPlane =
{
	.data =
	{
		PointPlane,
		8,
		PolygonPlane,
		6,
		AttributePlane
	}
};

/* Call this function in you code to display all objects */
static __jo_force_inline void       display_board_mesh(void)
{
	jo_3d_mesh_draw(&MeshPlane);
}

#endif /* !__3D_MODELBOARD_H__ */
