/*
   3D model generated by Jo Map Editor v6.1
*/

#ifndef __3D_MODELLEGS_H__
# define __3D_MODELLEGS_H__

static POINT    PointGrp5[] =
{
	{1603413, 3276800, 1615154},
	{1603413, 3276800, 1615154},
	{1603413, 3276800, 1615154},
	{336042, 1167055, 492152},
	{812037, 340523, 24309},
	{284958, 202849, -378665},
	{-78759, 367588, 125878},
	{1055679, 226126, 748228},
	{891910, -4695, 1408175},
	{1209638, -3219, 517199},
	{137279, 109070, 1050042},
	{-280487, 20646, 166716},
	{-52814, 374012, 87421},
	{549510, 371037, 540995},
	{-16132, 1141385, 103120},
	{656852, 378292, -53205},
	{690406, 1145670, -37505},
	{22906, 383443, 68697},
	{-20878, 1150816, 84397},
	{-1287333, 116392, -756191},
	{-1251146, 1175641, 427967},
	{-678857, 300780, 239001},
	{-901493, 233828, -397476},
	{-1606186, 278326, -204936},
	{-893644, 149874, 965362},
	{-1419722, -65115, 1404281},
	{-660301, -94628, 841076},
	{-1830181, 145337, 698660},
	{-1423220, 441245, -184396},
	{-1180651, 358779, 524752},
	{-1326512, 1197866, -91511},
	{-759695, 358358, 91803},
	{-665562, 1115372, 182958},
	{-1349465, 441341, -157314},
	{-1319040, 1207996, -108935},
};

static POLYGON    PolygonGrp5[] =
{
	{{37444, 42108, -33462}, {4, 5, 6, 6}},
	{{-2718, -1372, -65465}, {11, 5, 9, 9}},
	{{-65465, -35014, 54799}, {12, 3, 14, 14}},
	{{-8124, -57831, -29335}, {13, 16, 3, 3}},
	{{-57831, -29335, -9478}, {16, 17, 18, 18}},
	{{57869, -28882, -10574}, {8, 7, 10, 10}},
	{{-1372, -65465, -35014}, {9, 10, 11, 11}},
	{{-10574, -42954, -4110}, {10, 4, 6, 6}},
	{{-42954, -4110, 49325}, {21, 22, 23, 23}},
	{{49325, -418, 9022}, {23, 22, 26, 26}},
	{{9022, 64910, -48620}, {28, 20, 30, 30}},
	{{1424, 43920, 25487}, {29, 32, 20, 20}},
	{{43920, 25487, -536}, {32, 33, 34, 34}},
	{{60374, 52178, 10798}, {25, 24, 27, 27}},
	{{-418, 9022, 64910}, {26, 27, 23, 23}},
	{{10798, -38154, -11738}, {27, 21, 23, 23}},
	{{-28882, -10574, -42954}, {7, 8, 9, 9}},
	{{-65465, -35014, 54799}, {12, 13, 3, 3}},
	{{-8124, -57831, -29335}, {13, 15, 16, 16}},
	{{-57831, -29335, -9478}, {16, 15, 17, 17}},
	{{-33462, -2718, -1372}, {6, 11, 10, 10}},
	{{57869, -28882, -10574}, {8, 10, 9, 9}},
	{{42108, -33462, -2718}, {5, 11, 6, 6}},
	{{-10574, -42954, -4110}, {10, 7, 4, 4}},
	{{37444, 42108, -33462}, {4, 9, 5, 5}},
	{{-28882, -10574, -42954}, {7, 9, 4, 4}},
	{{52178, 10798, -38154}, {24, 25, 26, 26}},
	{{9022, 64910, -48620}, {28, 29, 20, 20}},
	{{1424, 43920, 25487}, {29, 31, 32, 32}},
	{{43920, 25487, -536}, {32, 31, 33, 33}},
	{{60374, 52178, 10798}, {25, 27, 26, 26}},
	{{10798, -38154, -11738}, {27, 24, 21, 21}},
	{{-42954, -4110, 49325}, {21, 26, 22, 22}},
	{{52178, 10798, -38154}, {24, 26, 21, 21}},
};

static ATTR    AttributeGrp5[] =
{
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, No_Option),
};

jo_3d_mesh    MeshGrp5 =
{
	.data =
	{
		PointGrp5,
		35,
		PolygonGrp5,
		34,
		AttributeGrp5
	}
};

/* Call this function in you code to display all objects */
static __jo_force_inline void       display_legs_mesh(void)
{
	jo_3d_mesh_draw(&MeshGrp5);
}

#endif /* !__3D_MODELLEGS_H__ */
